// flow-typed signature: 6ec32de9e641ac1febdfa9b8695525a7
// flow-typed version: <<STUB>>/eslint-config-react_v^1.1.7/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-react/index' {
  declare module.exports: $Exports<'eslint-config-react'>;
}
declare module 'eslint-config-react/index.js' {
  declare module.exports: $Exports<'eslint-config-react'>;
}
